global using Orleans;
global using Grains.Hubs;
global using Grains.Interfaces;
global using Grains.Interfaces.Abstractions;
global using Backend.Data;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Shared.Extensions;
global using Microsoft.AspNetCore.ResponseCompression;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using System.Text;
global using Backend.Services;
global using Microsoft.Azure.Cosmos;
global using System.Net;
global using Microsoft.AspNetCore.Server.Kestrel.Core;
global using User = Backend.Data.User;